logic/urls.py
from django.urls import path
from django.urls import include
from logic import views

app_name = 'logic'


urlpatterns = [
]

ratonGato/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from logic import views

urlpatterns = [
	path('', views.index, name='landing'),
    path('index/', views.index, name='landing'),
    path('admin/', admin.site.urls),
	path('login/', views.login_service, name='login'),
	path('signup/', views.signup_service, name='signup'),
	path('counter/', views.counter_service, name='counter'),
	path('join_game/', views.join_game_service, name='join_game'),
    path('join_game/<int:game_id>', views.join_game_service, name='join_game'),
	path('logout/', views.logout_service, name='logout'),
    path('get_move_service/', views.get_move_service, name='get_move'),
	path('create_ai_game/', views.create_ai_game_service, name='create_ai_game'),
	path('create_game/', views.create_game_service, name='create_game'),
	path('select_game/', views.select_game_service, name='select_game'),
    path('select_game/<int:game_id>', views.select_game_service, name='select_game'),
    path('replay_game/', views.replay_game_service, name='replay_game'),
    path('replay_game/<int:game_id>', views.replay_game_service, name='replay_game'),
	path('play/', views.show_game_service, name='show_game'),
    path('move/', views.move_service, name='move'),
]

logic/forms.py
from django import forms
from django.contrib.auth.models import User
from datamodel.models import Move

class LoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'password',)

class SignupForm(forms.ModelForm):
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'password', 'password2')

class MoveForm(forms.Form):
    origin = forms.IntegerField()
    target = forms.IntegerField()

    class Meta:
        model = Move
        fields = ('origin', 'target',)

    def is_valid(self):
        non_valid_pos = [1,3,5,7,8,10,12,14,17,19,21,23,24,26,28,30,33,35,37,39,40,42,44,46,49,51,53,55,56,58,60,62]

        valid = super(MoveForm, self).is_valid()

        if not valid:
            return valid

        if self.cleaned_data['origin'] < 0 or self.cleaned_data['origin'] > 63:
            return False
        if self.cleaned_data['target'] < 0 or self.cleaned_data['target'] > 63:
            return False
        if self.cleaned_data['origin'] in non_valid_pos or self.cleaned_data['target'] in  non_valid_pos:
            return False

        return True

templates/mouse_cat/base.html
{% load staticfiles %}
<html id= doc>
<head>
    {% block extra_css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    {% endblock extra_css %}

    {% block extra_js %}

    {% endblock extra_js %}

    {% block extra_head %}

    {% endblock extra_head %}
    <title>{% block title %}PSI 2019-2020: Example of application{% endblock %}</title>
</head>

<body id="body">
    <div id="totalheader">
        <div id="title">
            {% block atitle %}<h1 id="header_h">Mouse vs. Cats application</h1>{% endblock atitle %}
        </div>

        <div id="header">
            {% if request.user.is_authenticated %}
                Welcome <span class="username">{{ request.user.username }}</span>!
            {% endif %}
        </div>
    </div>

    <hr id="linea_div" />
	<div>
	<div id="menu">
    	<h1 id="headerservice">Service catalog</h1>

    	<ul>
		    {% if user.is_authenticated %}
                <li><a href="{% url 'logout' %}">Logout</a></li>
                <li><a href="{% url 'create_game' %}">Create game</a></li>
                <li><a href="{% url 'create_ai_game' %}">Create game (AI)</a></li>
                <li><a href="{% url 'select_game' %}">Game list</a></li>
                <li><a href="{% url 'counter' %}">Counter</a></li>
            {% else %}
                <li><a href="{% url 'login' %}">Login</a></li>
                <li><a href="{% url 'signup' %}">Signup</a></li>
                <li><a href="{% url 'counter' %}">Counter</a></li>
            {% endif %}
    	</ul>
	</div>
	    {% block content %}
	    {% endblock content %}
	</div>
  <div id="footer">
      <p id="footertext">All rights reserved</p>
    {% block footer %}
    {% endblock footer %}
  </div>
</body>
</html>

templates/mouse_cat/counter.html
{% extends "mouse_cat/base.html" %}

{% block content %}
<div id="content_counter">
    <h1 id="header_counter">Error counter</h1>
    <p id="text_counter">Number of errors: <b>{{ counter_global }}</b></p>
    <p id="link_counter"><a href="{% url 'landing' %}">Return to homepage</a></p>
</div>
{% endblock content %}

templates/mouse_cat/error.html
{% extends "mouse_cat/base.html" %}

{% block content %}
<div id="content">
    <h1>Error</h1>
    <p class="error">{{ msg_error }}</p>
    <p><a href="{% url 'landing' %}">Return to homepage</a></p>
</div>
{% endblock content %}

templates/mouse_cat/game.html
{% extends "mouse_cat/base.html" %}
{% load staticfiles %}


{% block extra_js %}
<script  src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js" ></script>
<script>
	var mov_status = 0;
	var origin = 0;
	var target = 0;

	function gen_move_form(){
        $("#chess_board td").click(function() {

 			if (mov_status == 0){
            	var column_num = parseInt( $(this).index() );
            	var row_num = parseInt( $(this).parent().index() );
				origin = row_num * 8 + column_num;
				mov_status = 1;
			}
			else {
				var column_num = parseInt( $(this).index() );
            	var row_num = parseInt( $(this).parent().index() );
				target = row_num * 8 + column_num;
				mov_status = 0;

				$("#id_origin").val(origin);
				$("#id_target").val(target);

				$("#move_form").submit();
			}
        });
    }

    $(document).ready(gen_move_form);
</script>
{% endblock extra_js %}

{% block content %}

	{% if message %}
		<div id="content">
			<h1>Game Over</h1>
			<p>{{ message }}</p>
	{% endif %}

	{% if not message %}
		<div id="content_game">
		    <h1 id="text_play">Play</h1>
		    <p id="p_play">Game: <b>{{ game.id }}</b></p>

			<p id= game_status>
				Cats: <b>{{ game.cat_user.username }}</b>
				<br/>
				Mouse: <b>{{ game.mouse_user.username }}</b>
				<br/>
				{% if game.cat_user.id == request.user.id %}
					{% if game.cat_turn %}
						It is your turn. Make a move!
						<br/>
					{% else %}
		                Waiting for the mouse...
						<br/>
		            {% endif %}
				{% endif %}

				{% if game.mouse_user.id == request.user.id %}
					{% if game.cat_turn %}
						Waiting for the cat...
						<br/>
					{% else %}
		        It is your turn. Make a move!
						<br/>
		            {% endif %}
				{% endif %}
				<a id="reload_button" href="{% url 'select_game' game.id %}">Reload</a>
			</p>
		    <form id="move_form" method="post" action="{% url 'move' %}">
		        {% csrf_token %}
		        <p>
		            Cats: <b>{{ game.cat_user.username }}</b>
		            {% if game.cat_user.id == request.user.id %}
		                <blockquote class="cat">
		                    {% if game.cat_turn %}
		                        {{ move_form }}
		                        <input type="submit" value="Move" />
		                    {% else %}
		                        Waiting for the mouse...
		                        <a style="margin-left:20px;font-weight:normal" href="{% url 'show_game' %}">Refresh</a>
		                    {% endif %}
		                </blockquote>
		            {% endif %}
		        </p>
		        <p>
		            Mouse: <b>{{ game.mouse_user.username }}</b>
		            {% if game.mouse_user.id == request.user.id %}
		                <blockquote class="mouse">
		                    {% if not game.cat_turn %}
		                        {{ move_form }}
		                        <input type="submit" value="Move" />
		                    {% else %}
		                        Waiting for the cat...
		                        <a style="margin-left:20px;font-weight:normal" href="{% url 'show_game' %}">Refresh</a>
		                    {% endif %}
		                </blockquote>
		            {% endif %}
		        </p>
		    </form>

		    {% if board %}
				 {% if game.cat_user.id == request.user.id %}
		                    {% if game.cat_turn %}
		                        <table id="chess_board">
		        					{% for item in board %}
		            					{% if forloop.counter0|divisibleby:8 %}<tr>{% endif %}
			    							{% if forloop.counter0 in odd_pos %}
		            							<td id="cell_{{ forloop.counter0}}" style='width:50px;border:1px solid #000000;text-align:center; background-color: white;height:50px'>
		                							{% if item ==  0 %}   &nbsp;
		                							{% elif item == 1 %}  <img src="{% static 'images/cat.jpg' %}" />
		                							{% else %}  <img src="{% static 'images/mouse.jpg' %}" /> {% endif %}
		            							</td>
			    							{% else %}
		            							<td id="cell_{{ forloop.counter0}}" style='width:50px;border:1px solid #000000;text-align:center;height:50px; background-color: black;'>
		                							{% if item ==  0 %}
		                							{% elif item == 1 %}  <img src="{% static 'images/cat.jpg' %}" />
		                							{% else %}  <img src="{% static 'images/mouse.jpg' %}" /> {% endif %}
		            							</td>
			    							{% endif %}
		            					{% if forloop.counter|divisibleby:8 or forloop.last %}</tr>{% endif %}
		        					{% endfor %}
		        				</table>
		                    {% else %}
		                        <table id="chess_board_2">
		        					{% for item in board %}
		            					{% if forloop.counter0|divisibleby:8 %}<tr>{% endif %}
			    							{% if forloop.counter0 in odd_pos %}
		            							<td id="cell_{{ forloop.counter0}}" style='width:50px;border:1px solid #000000;text-align:center; background-color: white;height:50px'>
		                							{% if item ==  0 %}   &nbsp;
		                							{% elif item == 1 %}  <img src="{% static 'images/cat.jpg' %}" />
		                							{% else %}  <img src="{% static 'images/mouse.jpg' %}" /> {% endif %}
		            							</td>
			    							{% else %}
		            							<td id="cell_{{ forloop.counter0}}" style='width:50px;border:1px solid #000000;text-align:center;height:50px; background-color: black;'>
		                							{% if item ==  0 %}
		                							{% elif item == 1 %}  <img src="{% static 'images/cat.jpg' %}" />
		                							{% else %}  <img src="{% static 'images/mouse.jpg' %}" /> {% endif %}
		            							</td>
			    							{% endif %}
		            					{% if forloop.counter|divisibleby:8 or forloop.last %}</tr>{% endif %}
		        					{% endfor %}
		        				</table>
		                    {% endif %}
		         {% endif %}

				 {% if game.mouse_user.id == request.user.id %}
		                    {% if not game.cat_turn %}
		                        <table id="chess_board">
		        					{% for item in board %}
		            					{% if forloop.counter0|divisibleby:8 %}<tr>{% endif %}
			    							{% if forloop.counter0 in odd_pos %}
		            							<td id="cell_{{ forloop.counter0}}" style='width:50px;border:1px solid #000000;text-align:center; background-color: white;height:50px'>
		                							{% if item ==  0 %}   &nbsp;
		                							{% elif item == 1 %}  <img src="{% static 'images/cat.jpg' %}" />
		                							{% else %}  <img src="{% static 'images/mouse.jpg' %}" /> {% endif %}
		            							</td>
			    							{% else %}
		            							<td id="cell_{{ forloop.counter0}}" style='width:50px;border:1px solid #000000;text-align:center;height:50px; background-color: black;'>
		                							{% if item ==  0 %}
		                							{% elif item == 1 %}  <img src="{% static 'images/cat.jpg' %}" />
		                							{% else %}  <img src="{% static 'images/mouse.jpg' %}" /> {% endif %}
		            							</td>
			    							{% endif %}
		            					{% if forloop.counter|divisibleby:8 or forloop.last %}</tr>{% endif %}
		        					{% endfor %}
		        				</table>
		                    {% else %}
		                        <table id="chess_board_2">
		        					{% for item in board %}
		            					{% if forloop.counter0|divisibleby:8 %}<tr>{% endif %}
			    							{% if forloop.counter0 in odd_pos %}
		            							<td id="cell_{{ forloop.counter0}}" style='width:50px;border:1px solid #000000;text-align:center; background-color: white;height:50px'>
		                							{% if item ==  0 %}   &nbsp;
		                							{% elif item == 1 %}  <img src="{% static 'images/cat.jpg' %}" />
		                							{% else %}  <img src="{% static 'images/mouse.jpg' %}" /> {% endif %}
		            							</td>
			    							{% else %}
		            							<td id="cell_{{ forloop.counter0}}" style='width:50px;border:1px solid #000000;text-align:center;height:50px; background-color: black;'>
		                							{% if item ==  0 %}
		                							{% elif item == 1 %}  <img src="{% static 'images/cat.jpg' %}" />
		                							{% else %}  <img src="{% static 'images/mouse.jpg' %}" /> {% endif %}
		            							</td>
			    							{% endif %}
		            					{% if forloop.counter|divisibleby:8 or forloop.last %}</tr>{% endif %}
		        					{% endfor %}
		        				</table>
		                    {% endif %}
		         {% endif %}
		    {% endif %}

		    <p id= return_homepage><a href="{% url 'landing' %}">Return to homepage</a></p>
		</div>
	{% endif %}
{% endblock content %}

templates/mouse_cat/index.html
{% extends "mouse_cat/base.html" %}

{% load staticfiles %}

{% block content %}
<div id="content">
</div>
{% endblock content %}

templates/mouse_cat/join_game.html
{% extends "mouse_cat/base.html" %}

{% block content %}
<div id="content">
    <h1>Join game</h1>
    {% if msg_error %}
        <p class="error">ERROR: {{ msg_error }}</p>
    {% else %}
        <p><b>{{ game.mouse_user.username }}</b> succesfully joined to game <b>{{ game.id }}</b>. The game can start!!!</p>
    {% endif %}
    <p><a href="{% url 'landing' %}">Return to homepage</a></p>
</div>
{% endblock content %}

templates/mouse_cat/login.html
{% extends "mouse_cat/base.html" %}

{% block content %}
<div id="content">
    <h1>Login</h1>
    Log in to continue:
    <form id="login_form" method="post" action="{% url 'login' %}">
        {% csrf_token %}
        {{ user_form.as_p }}<br/>
        <input type="hidden" name="return_service" value="{{ return_service }}" />
        <input type="submit" value="Log-In" />
    </form>

    <p><a href="{% url 'landing' %}">Return to homepage</a></p>
</div>
{% endblock content %}

templates/mouse_cat/logout.html
{% extends "mouse_cat/base.html" %}

{% block content %}
<div id="content">
    <h1>Logout</h1>
    <p>Dear <b>{{ user }}</b>, you have been successfully logged out</p>
    <p><a href="{% url 'landing' %}">Return to homepage</a></p>
</div>
{% endblock content %}

templates/mouse_cat/new_game.html
{% extends "mouse_cat/base.html" %}

{% block content %}
<div id="content">
    <h1>Create game</h1>  
    <p>Game <b>{{ game.id }}</b> succesfully created by user <b>{{ game.cat_user.username }}</b></p>
    <p><a href="{% url 'landing' %}">Return to homepage</a></p>
</div>
{% endblock content %}

templates/mouse_cat/replay_game.html
{% extends "mouse_cat/base.html" %}
{% load staticfiles %}


{% block extra_js %}
<script src='https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js'></script>
<script>

  function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
  }

  function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
  }
  $.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    }
  });

  var shift;
  var option_b;

  $(document).on('mouseover', 'input', function() {
    option_b = this.id;
  });

  function replay_prev_next() {

    var xhttp = new XMLHttpRequest();
    xhttp.onreadystatechange = function() {

      if (this.readyState == 4 && this.status == 200) {
        var response_get_move = JSON.parse(this.responseText);

        if(response_get_move.next == 0 && response_get_move.winner == null){
          alert("Error: Bad move fetching");
        }

        if(response_get_move.previous == 0 && response_get_move.origin == null){
          alert("Error: Bad move fetching");
        }

        if(response_get_move.origin != null && response_get_move.winner == null){
          document.getElementById("cell_"+response_get_move.target.toString()).innerHTML = document.getElementById("cell_"+response_get_move.origin.toString()).innerHTML;
          document.getElementById("cell_"+response_get_move.origin.toString()).innerHTML = null;
        }

        if(response_get_move.winner != null){
          document.getElementById("cell_"+response_get_move.target.toString()).innerHTML = document.getElementById("cell_"+response_get_move.origin.toString()).innerHTML;
          document.getElementById("cell_"+response_get_move.origin.toString()).innerHTML = null;
          alert(response_get_move.winner + " has won the game!");
        }
      }
    };

    var aux_form = new FormData();
    if (option_b == "replay_options_next"){
      shift = 1;
    }

    else if (option_b == "replay_options_prev"){
      shift = -1;
    }

    aux_form.append("shift", shift);
    xhttp.open("POST", "{% url 'get_move' %}", true);
    xhttp.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
    xhttp.send(aux_form);

  };

  var auto_play = 0;

  function automatic_play(){
    auto_play = setInterval(function() {

      var xhttp = new XMLHttpRequest();
      xhttp.onreadystatechange = function() {

        if (this.readyState == 4 && this.status == 200) {
          var response_get_move = JSON.parse(this.responseText);

          if(response_get_move.next == 0 && response_get_move.winner == null){
            alert("Error: Bad move fetching");
          }

          if(response_get_move.previous == 0 && response_get_move.origin == null){
            alert("Error: Bad move fetching");
          }

          if(response_get_move.origin != null && response_get_move.winner == null){
            document.getElementById("cell_"+response_get_move.target.toString()).innerHTML = document.getElementById("cell_"+response_get_move.origin.toString()).innerHTML;
            document.getElementById("cell_"+response_get_move.origin.toString()).innerHTML = null;
          }

          if(response_get_move.winner != null){
            document.getElementById("cell_"+response_get_move.target.toString()).innerHTML = document.getElementById("cell_"+response_get_move.origin.toString()).innerHTML;
            document.getElementById("cell_"+response_get_move.origin.toString()).innerHTML = null;
            alert(response_get_move.winner + " has won the game!");
          }
        }
      };

      var aux_form = new FormData();
      shift = 1;

      aux_form.append("shift", shift);
      xhttp.open("POST", "{% url 'get_move' %}", true);
      xhttp.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
      xhttp.send(aux_form);

    } ,1000);
  };

</script>
{% endblock extra_js %}

{% block content %}
<div id="content">
    <h1 id="text_replay">Replay</h1>
    <p id="p_replay">Game: <b>{{ game.id }}</b></p>

	<p id= game_status>
		Cats: <b>{{ game.cat_user.username }}</b>
		<br/>
		Mouse: <b>{{ game.mouse_user.username }}</b>
		<br/>
  </p>

    {% if board %}
    <table id="chess_board_replay">
      {% for item in board %}
        {% if forloop.counter0|divisibleby:8 %}<tr>{% endif %}
	    {% if forloop.counter0 in odd_pos %}
        <td id="cell_{{ forloop.counter0}}" style='width:50px;border:1px solid #000000;text-align:center; background-color: white;height:50px'>
          {% if item ==  0 %}   &nbsp;
          {% elif item == 1 %}  <img src="{% static 'images/cat.jpg' %}" />
          {% else %}  <img src="{% static 'images/mouse.jpg' %}" /> {% endif %}
        </td>
	    {% else %}
        <td id="cell_{{ forloop.counter0}}" style='width:50px;border:1px solid #000000;text-align:center;height:50px; background-color: black;'>
          {% if item ==  0 %}
          {% elif item == 1 %}  <img src="{% static 'images/cat.jpg' %}" />
          {% else %}  <img src="{% static 'images/mouse.jpg' %}" /> {% endif %}
        </td>
	    		{% endif %}
            {% if forloop.counter|divisibleby:8 or forloop.last %}</tr>{% endif %}
        	{% endfor %}
        </table>
    <div>
      <td><input id= replay_options_prev type="submit" value="Previous" name="_previous" onclick = "replay_prev_next();"></td>
      <td><input id= replay_options_next type="submit" value="Next" name="_next" onclick = "replay_prev_next();"></td>
      <td><input id= replay_options_play type="submit" value="Play" name="_play" onclick = "automatic_play();"></td>
      <td><input id= replay_options_pause type="submit" value="Pause" name="_pause" onclick = clearInterval(auto_play);></td>
    </div>
    <p id= return_homepage><a href="{% url 'landing' %}">Return to homepage</a></p>
    <input type="hidden" id="custId" name="custId" value="0">
    {% endif %}
</div>
{% endblock content %}

templates/mouse_cat/select_game.html
{% extends "mouse_cat/base.html" %}

{% block content %}
<div id="content">
    <h1>Select game</h1>
    <p>
        {% if games %}
            Available games:
            <ul id="linklist">
            {% for game in games %}
                <li>
                  Game {{ game.id }}|&nbsp;&nbsp;&nbsp;Cat: {{ game.cat_user }}&nbsp;&nbsp;&nbsp;Mouse: {{ game.mouse_user }} &nbsp;&nbsp;&nbsp;
                  <a href="{% url 'select_game' game.id %}">Play</a>
                  &nbsp;&nbsp;&nbsp;
                  <a href="{% url 'join_game' game.id %}">Join</a>
                  &nbsp;&nbsp;&nbsp;
                  <a href="{% url 'replay_game' game.id %}">Replay</a>
                </li>

            {% endfor %}
            </ul>
        {%  else %}
            No available games.
        {% endif %}
    </p>
    <p><a href="{% url 'landing' %}">Return to homepage</a></p>
</div>
{% endblock content %}

templates/mouse_cat/select_game_old.html
{% extends "mouse_cat/base.html" %}

{% block content %}
<div id="content">
    <h1>Select game</h1>
    <p>
        {% if as_cat %}
            Games as cat:
            <ul>
            {% for game in as_cat %}
                <li> <a href="{% url 'select_game' game.id %}">{{ game }}</a></li>
            {% endfor %}
            </ul>
        {%  else %}
            No games as cat
        {% endif %}
    </p>

    <p>
        {% if as_mouse %}
            Games as mouse:
            <ul>
            {% for game in as_mouse %}
                <li> <a href="{% url 'select_game' game.id %}">{{ game }}</a></li>
            {% endfor %}
            </ul>
        {%  else %}
            No games as mouse
        {% endif %}
    </p>

    <p><a href="{% url 'landing' %}">Return to homepage</a></p>
</div>
{% endblock content %}

templates/mouse_cat/signup.html
{% extends "mouse_cat/base.html" %}

{% block content %}
<div id="content">
    <h1>Signup user</h1>
    {% if user_form %}
        <form id="user_form" method="post" action="{% url 'signup' %}">
            {% csrf_token %}
            {{ user_form.as_p }}<br/>
            <input type="submit" name="submit" value="Register" />
        </form>
    {% else %}
        <p>User successfully created</p>
    {% endif %}
    <p><a href="{% url 'landing' %}">Return to homepage</a></p>
</div>
{% endblock content %}